apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube101
  name: kube101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube101
  template:
    metadata:
      labels:
        app: kube101
    spec:
      containers:
      - image: nikolaies/kube101:v2
        name: kube101
        env:
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
