apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube101
  name: kube101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube101
  template:
    metadata:
      labels:
        app: kube101
    spec:
      containers:
      - image: nikolaies/kube101:v1
        name: kube101
        env:
        - name: PASSWORD
          valueFrom:
              secretKeyRef:
                name: kube101-secret
                key: password
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: file-volume
          mountPath: "/root/goApp/files/custom.config"
          subPath: "custom.config"
          readOnly: true
    volumes:
      - name: file-volume
        configMap:
          name: kube101-cm
          items:
            - key: custom.config
              path: custom.config
