apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube101
  name: kube101
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube101
  template:
    metadata:
      labels:
        app: kube101
    spec:
      containers:
      - image: nikolaies/kube101:v3
        name: kube101
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            memory: 500Mi
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: kube101-secret
              key: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: file-volume
          mountPath: "/root/files/custom.config"
          subPath: custom.config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
      volumes:
      - name: file-volume
        configMap:
          name: kube101-cm
          items:
            - key: custom.config
              path: custom.config

