apiVersion: v1
kind: Service
metadata:
  name: kube101-nodeport
spec:
  type: NodePort
  selector:
    app: kube101
  ports:
    - port: 8080          # The port that will be exposed internally in the cluster
      targetPort: 8080     # The port on the pod that the service should forward traffic to
      nodePort: 30001    # The port that will be exposed on each node of the cluster (must be between 30000-32767)

