apiVersion: v1
kind: Pod
metadata:
  name: kube101
  labels:
    app: kube101
spec:
  containers:
  - name: kube101
    image: nikolaies/kube101:v1
    ports:
    - containerPort: 8080
    env:
    - name: POD_NAME
      valueFrom:
          fieldRef:
            fieldPath: metadata.name
