apiVersion: v1
kind: Service
metadata:
  name: kube101-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.234
  selector:
    app: kube101
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
