name: Docker Image CI

on:
  push:
    tags:
      - v*


jobs:

  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        submodules: recursive
    - name: Build the Docker image
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set version
      id: version
      run: echo "::set-output name=version::$(if [[ '${{github.event_name}}' == 'pull_request' ]]; then echo pr-${{github.event.number}}; else echo ${{github.ref_name}}; fi)"
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./goApp
        file: ./goApp/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          nikolaies/kube101:${{ steps.version.outputs.version }}
